### ISSUE TITLE
FAQ: My SSHID keeps changing every boot

### ISSUE THREAD

**Issue by otavio** [shellhub-io/shellhub-io.github.io#17]
**My SSHID keeps changing every boot**

One common reason for this to happen is when using Ethernet over USB. This happens automatically on Raspberry Pi OS for example as the Raspberry Pi Zero has no Ethernet hardware, so there is no hard-coded Ethernet MAC address.

An workaround for the issue is to use the last MAC as a static one. This can be done using following code:
```shell
echo 'options g_ether host_addr='$(dmesg | awk '/: HOST MAC/{print $NF}')' dev_addr='$(dmesg | awk '/: MAC/{print $NF}') | sudo tee /etc/modprobe.d/g_ether.conf
```

**Comment by Ryce358** [comment]
This worked for me perfectly on both dhcpcd and networkd pi implementations.  It only affects the usb MAC address so anything on the wlan0 side is unaffected and should still be the hardware Mac address,  Thanks Otavio!

**Comment by Ryce358** [comment]
If it is possible to simply copy the wlan0 MAC address over to the USB without any adverse affects, then this would be the best way of keeping track of devices.  Or in the long run, perhaps a method of setting the index of the interface to use for the MAC address?

**Comment by otavio** [comment]
Yes, we have an issue to allow you to set a custom device identity (https://github.com/shellhub-io/shellhub/issues/259). Changing the `ifindex` used may be difficult for people to understand at first and we wish to keep ShellHub as simple as possible to use.

**Comment by Ryce358** [comment]
Do we still need to use the workaround above or has another fix been implemented?

**Comment by otavio** [comment]
@Ryce358 this is not a workaround but a way to circumvent the use of a device which does not provide a static MAC address by default. Do you have any suggestion on how to better address the issue?

**Comment by Ryce358** [comment]
@otavio Not specifically, no, I was just confused by this being closed and thought you'd added something that allowed me to avoid the code above but I'll continue deploying with it. Thanks.

**Comment by otavio** [comment]
Ahh ok. We merged the doc change, so now it is public:

http://docs.shellhub.io/troubleshooting/#my-sshid-keeps-changing-every-boot-when-using-ethernet-over-usb
